spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectment
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

application:
  security:
    secret-key: UxCSli43hlRTUV4AVAr0do+TCvlhaSP0082YP1GKmG3fyJ4DilrYEpVooqlKHazlRz/paDR9ROCytG1D7RE86hfBLL+RIWGwdlh0Wonhhp3a1a/wIZZ0moda3QycXM9H8Qk4MtXwcInGIY3AqCnTQW8gtYDxKQ0Hz13LavGU+SxD7BWUUVb0Oy/rh62QznrZvAlveqOYsVEAj4/ZFfobW9PfpFN6og9yXYHJwnRh8EWlzKcQ7ON6XHI90x5jc8FaEKpRMzlDuJ8/zT/ojyRrpsVf28ZgmkVBhr/Y/InR5fFJwNiFmkeNNhWmHtqCsP9niKzgF2biETtwjRjtGGnvUtV6+pmAicJmWo2u5aMlfVE=
    expiration: 1200000
